[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
runs = 100
depth = 100
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
